USE MASTER;

DROP DATABASE ASM1;

CREATE DATABASE ASM1;

USE ASM1;


/* Criação da tabela de produtos */

CREATE TABLE PRODUCTS(
	ID_PRODUCTS INT NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	AMOUNT NUMERIC(15,4) NOT NULL,
	PRICE NUMERIC(15,4) NOT NULL,
	CONSTRAINT PK_PRODUCTS PRIMARY KEY(ID_PRODUCTS)
);

CREATE SEQUENCE SEQUENCE_PRODUCTS AS INTEGER START WITH 1 INCREMENT BY 1;

/* Criação da tabela de clientes */

CREATE TABLE CLIENTS(
	ID_CLIENTS INT NOT NULL, 
	NAME VARCHAR(100) NOT NULL,
	DOCUMENT VARCHAR(14) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	TELEPHONE VARCHAR(20),
	CONSTRAINT PK_CLIENTS PRIMARY KEY(ID_CLIENTS)
);

CREATE SEQUENCE SEQUENCE_CLIENTS AS INTEGER START WITH 1 INCREMENT BY 1;

/* Criação da tabela de pedidos */

CREATE TABLE ORDERS(
	ID_ORDERS INT NOT NULL,
	IDFK_CLIENTS INT NOT NULL,
	DATE DATETIME,
	STATUS SMALLINT NOT NULL, -- 0 [nao pago] / 1 [pago]
	CONSTRAINT PK_ORDERS PRIMARY KEY(ID_ORDERS),
	CONSTRAINT FK_ORDERS_CLIENTS FOREIGN KEY(IDFK_CLIENTS) REFERENCES CLIENTS(ID_CLIENTS)
);

CREATE INDEX IX_ORDERS_CLIENTS ON ORDERS(IDFK_CLIENTS);

CREATE SEQUENCE SEQUENCE_ORDERS AS INTEGER START WITH 1 INCREMENT BY 1;

/* Criação da tabela de items de pedido */

CREATE TABLE ORDERS_ITEMS(
	ID_ORDERS_ITEM INT IDENTITY(1,1) NOT NULL,
	IDFK_ORDERS INT NOT NULL,
	IDFK_PRODUCTS INT NOT NULL,
	SEQUENCE INT NOT NULL,
	AMOUNT NUMERIC(15,4) NOT NULL,
	CONSTRAINT PK_ORDERS_ITEMS PRIMARY KEY(ID_ORDERS_ITEM),
	CONSTRAINT FK_ORDERS_ITEMS_ORDERS FOREIGN KEY(IDFK_ORDERS) REFERENCES ORDERS(ID_ORDERS) ON DELETE CASCADE,
	CONSTRAINT FK_ORDERS_ITEMS_PRODUCTS FOREIGN KEY(IDFK_PRODUCTS) REFERENCES PRODUCTS(ID_PRODUCTS)
);

CREATE INDEX IX_ORDERS_ITEM_ORDERS ON ORDERS_ITEMS(IDFK_ORDERS);
CREATE INDEX IX_ORDERS_ITEM_PRODUCTS ON ORDERS_ITEMS(IDFK_PRODUCTS);